---

# Install Solr .
- name: SolrCloud | Install
  include_tasks: install.yml
  when: "solr_version.split('.')[0] >= '5'"

# Configure solr.
- name: SolrCloud | Config
  include_tasks: configure.yml
  when: "solr_version.split('.')[0] >= '5'"

# Create cores, if any are configured.
- include_tasks: cores.yml
  when: "solr_cores and solr_version.split('.')[0] >= '5'"

- name: SolrCloud | Remove unused example
  include_tasks: trim-fat.yml
  when: solr_remove_cruft

- name: SolrCloud | Start solr
  service:
    name: "{{ solr_service_name }}"
    state: "{{ solr_service_state }}"
    sleep: 5

- name: SolrCloud | Wait to fully startup before continue
  uri:
    url: "http://{{ solr_host }}:{{ solr_port }}/solr"
    status_code: 200
  retries: "100"
  delay: "1"
  register: result
  until: result.status == 200
  changed_when: false